### ISSUE TITLE
Add different circuits to list and create new files for each one.

### ISSUE THREAD

**Issue by Xndr7** [Xndr7/awesome-circuits#1]
We need to add new circuits to the lists as well as make new sub folders for each type of circuit viz. Analog, Digital and Mixed Signal.
Feel free to contribute after following the guidelines and format mentioned strictly. 
Any basic circuit will also do.
Please update the README.md file as well so as to avoid duplicates and remember to add yourself as a contributor.
Here's to creating something wonderful and helpful :clinking_glasses:

**Comment by kburk1997** [comment]
Would these be good starting points for analog:

- Operational amplifier configurations (inverting, non-inverting, Miller integrator, differential amplifier)
- Half and full wave diode rectifiers
- FET current mirrors
- Voltage regulators

I can get started on one of these.

**Comment by Xndr7** [comment]
Yes @kburk1997!
I think Operational Amplifiers would be a good starting point for sure!
Feel free to send a PR at your convenience! :+1:

**Comment by j-kon** [comment]
I think Operational Amplifiers would be a good starting point for sure!
Feel free to send a PR at your convenience!
